language: groovy
jdk:
- oraclejdk7
branches:
  only:
  - master
before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- GRAILS_VERSION=`grep '^\s*app.grails.version' application.properties | sed -e 's/^\s*app\.grails\.version=//g'
  | tr -d "\r"`
- echo "GRAILS_VERSION:$GRAILS_VERSION"
- gvm install grails $GRAILS_VERSION || true
before_script:
- GRAILS_VERSION_NUMBER=`echo $GRAILS_VERSION | sed -e 's/\.[0-9]*$//g' -e 's/\.//g'`
- echo "GRAILS_VERSION_NUMBER:$GRAILS_VERSION_NUMBER"
- GRAILS_SETTINGS_FILE="travis_grails_settings_new.groovy"
- if [ "$GRAILS_VERSION_NUMBER" -lt "23" ]; then GRAILS_SETTINGS_FILE="travis_grails_settings_old.groovy";
  fi;
- echo "GRAILS_SETTINGS_FILE:$GRAILS_SETTINGS_FILE"
- mkdir -p ~/.grails; wget -q -O ~/.grails/settings.groovy https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/$GRAILS_SETTINGS_FILE
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings.xml
- MAVEN_REPO="ala-repo-snapshot"
- MAVEN_REPO_URL="http://ala-wonder.it.csiro.au/nexus/content/repositories/snapshots/"
- grep '^\s*app\.version=' ./application.properties | grep -q "\-SNAPSHOT"; if [ "$?" = "1" ]; then MAVEN_REPO="ala-repo-release"; MAVEN_REPO_URL="http://ala-wonder.it.csiro.au/nexus/content/repositories/releases/"; fi;
- echo "MAVEN_REPO:$MAVEN_REPO"
- echo "MAVEN_REPO_URL:$MAVEN_REPO_URL"

script:
- grails clean && grails refresh-dependencies --non-interactive && grails prod war
  --non-interactive
after_success: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && cp grails-release-plugin-bug-workaround_pom.xml pom.xml && APP_VERSION=`grep "^\s*app\.version=" ./application.properties | sed -e "s/^\s*app\.version=//g" | tr -d "\r"` && mvn versions:set -DnewVersion=$APP_VERSION && mvn deploy:deploy-file -DpomFile=pom.xml -Dfile=target/bie-webapp2-0.2.war -DrepositoryId=$MAVEN_REPO -Durl=$MAVEN_REPO_URL'

env:
  global:
  - secure: BLEaX/O71sq14ZVodGe1h+8GfyfXUg+zqMzSxvm2XmmZFu3aM9LXneUqWJL3own7GCAQNpCRMqo9N880InDOksZHNStOtLKDopI3I4D/KKYq+zYM7/55Zpnh/6wGIkddpeRQ/BZwwayffy+zAWu6DstGGf5EcdveuJ2YmtLng6k=
  - secure: w2nHPcU6Zo5MGmiLWxsbUF/YlLigcZycncEgJr184QoYeGr/ya7BMxjuIRtmzKRbS2JX1+d27ZXzji/32VEGPavfsVzm1pdn8YyA/oOzoXBtQNL/dlxtbBQZx22eRwb+93K5cdwIx3w74XdAncH61W90a0liasA772xv/aM1nU4=
